---
title: "Visual4Model5"
author: "Zehao Qian"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Visualization for ABM Model version 5

## Environment Setup

```{r}
# --------------------------------------------------------
# clear the environment var area
rm(list = ls())
# clear all plots
graphics.off()
# clear the console area
cat("\014")
# --------------------------------------------------------
# name of pic output folder
folder_name <- "./pic"

# check if the folder already exists
if (dir.exists(folder_name)) {
  unlink(folder_name, recursive = TRUE)
}

# create a new folder
dir.create(folder_name)
```

## Read data with 'Fread' function

```{r message=FALSE, warning=FALSE}
library(data.table)
model5.results = fread("./model5results.csv")
```

## Filter data only when p=0.01, 0.02, 0,03

```{r message=FALSE, warning=FALSE}
library(dplyr)
p.change.research = model5.results %>% filter(AgentID == 100, Step == 100)
p.change.research
```

## Change the data to long format

```{r}
library(tidyr)
p.change.research.long <- p.change.research %>%
  pivot_longer(cols = starts_with("Steps_to"), 
               names_to = "Step_Percent", 
               values_to = "Steps_Count")
p.change.research.long
```

## Draw Box Plot

### Generate Box plot with "esquisse"

```{r}
# library(plotly)
# library(esquisse)
# esquisser()
```

```{r}
library(ggplot2)
box = ggplot(p.change.research.long) +
  aes(x = Step_Percent, y = Steps_Count, fill = p) +
  geom_boxplot() +
  scale_fill_gradient() +
  labs(
    x = "Proportion Reach",
    y = "Steps Count",
    title = "Boxplot for Potential User Acceptance Ratio",
    subtitle = "When the acceptance probability of innovator changes (p)"
  ) +
  theme_light() +
  theme(
    plot.title = element_text(face = "bold", hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5)
  ) +
  facet_wrap(vars(p))
```

```{r}
library(svglite)
ggsave("./pic/boxplot_p_change.svg", plot = box, device = "svg", height = 9, width = 16)
```
