---
title: "P Change Research"
author: "Zehao Qian"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Data Set: Simulation 1

-   N = 1000

-   p = 0.01, 0.02, 0.03

-   q = 0.3

-   Iteration = 25

```{r}
gc()
rm(list = ls())
graphics.off()
cat("\014")
```

```{r}
library(data.table)
simulation1_results = fread("./simulation1.csv")
```

```{r}
library(dplyr)
library(tidyr)

data.p.change = simulation1_results %>%
  filter(AgentID == 100, Step == 100)


data.p.change.long = data.p.change %>%
  pivot_longer(cols = starts_with("Steps_to"), 
               names_to = "Step_Percent", 
               values_to = "Steps_Count")
```

```{r}
library(plotly)
library(esquisse)
esquisser(data.p.change.long)
```

```{r fig.height=9, fig.width=16}
library(ggplot2)
box = ggplot(data.p.change.long) +
  aes(x = Step_Percent, y = Steps_Count, fill = p) +
  geom_boxplot() +
  scale_fill_gradient() +
  labs(
    x = "Proportion Reach",
    y = "Steps Count",
    title = "Boxplot for Potential User Acceptance Ratio",
    subtitle = "When the acceptance probability of innovator changes (p)"
  ) +
  theme_light() +
  theme(
    plot.title = element_text(face = "bold", hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5)
  ) +
  facet_wrap(vars(p))

box
```

```{r}

```
