---
title: "Agent Neighbour Stat"
author: "Zehao Qian"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Simulation 1**

-   N = 1000

-   p = 0.01, 0.02, 0.03

-   q = 0.3

-   Iteration = 25

```{r}
# --------------------------------------------------------
gc()
rm(list = ls())
graphics.off()
cat("\014")
# --------------------------------------------------------
folder_name <- "./agent_neighbour_record"
if (dir.exists(folder_name)) {
  unlink(folder_name, recursive = TRUE)
}
dir.create(folder_name)
```

```{r}
library(data.table)

# Loop through simulation1.csv to simulation6.csv
for (sim_num in 1:6) {
  # Clear memory before processing each file
  gc()
  
  # Read the simulation file
  simulation_file <- paste0("./simulation", sim_num, ".csv")
  simulation_results <- fread(simulation_file)
  RunID_list <- unique(simulation_results$RunId)
  
  # Create a new data table to store results
  results <- data.table(
    RunId = integer(),
    neighbors_inf_mean = numeric(),
    neighbors_inf_max = numeric(),
    neighbors_inf_min = numeric(),
    neighbors_non_inf_mean = numeric(),
    neighbors_non_inf_max = numeric(),
    neighbors_non_inf_min = numeric()
  )
  
  for (run_id in RunID_list) {
    data.id0 <- simulation_results[RunId == run_id & Step == 0]
    
    data.id0.inf <- data.id0[Influencer == TRUE]
    data.id0.non_inf <- data.id0[Influencer == FALSE]
    
    neighbors_inf.mean <- mean(data.id0.inf$Neighbors_number)
    neighbors_inf.max <- max(data.id0.inf$Neighbors_number)
    neighbors_inf.min <- min(data.id0.inf$Neighbors_number)
    neighbors_non_inf.mean <- mean(data.id0.non_inf$Neighbors_number)
    neighbors_non_inf.max <- max(data.id0.non_inf$Neighbors_number)
    neighbors_non_inf.min <- min(data.id0.non_inf$Neighbors_number)
    
    results <- rbindlist(list(
      results,
      data.table(
        RunId = run_id,
        neighbors_inf_mean = neighbors_inf.mean,
        neighbors_inf_max = neighbors_inf.max,
        neighbors_inf_min = neighbors_inf.min,
        neighbors_non_inf_mean = neighbors_non_inf.mean,
        neighbors_non_inf_max = neighbors_non_inf.max,
        neighbors_non_inf_min = neighbors_non_inf.min
      )
    ))
  }
  
  # Save results to a CSV file
  output_file <- file.path(folder_name,
                           paste0("results_simulation", sim_num, ".csv"))
  fwrite(results, output_file)
  # print the results
  print(results)
  # Print a message to indicate progress
  cat("Processed and saved results for simulation", sim_num, "\n")
  
  # Clear large objects from memory
  rm(simulation_results,
     results,
     data.id0,
     data.id0.inf,
     data.id0.non_inf)
  gc()
}

cat("All simulations processed and results saved in",
    folder_name,
    "\n")
```

```{r}

```
