---
title: "Network Visualization"
author: "Zehao Qian"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Network Visualization for Model 7 Result

```{r}
# --------------------------------------------------------
# clear the environment var area
rm(list = ls())
# clear all plots
graphics.off()
# clear the console area
cat("\014")
# --------------------------------------------------------
# name of pic output folder
folder_name <- "./pic_network_graph"

# check if the folder already exists
if (dir.exists(folder_name)) {
  unlink(folder_name, recursive = TRUE)
}

# create a new folder
dir.create(folder_name)
```

**Simulation 1**

-   N = 1000

-   p = 0.01, 0.02, 0.03

-   q = 0.3

-   Iteration = 25

```{r message=FALSE, warning=FALSE}
library(data.table)
simulation1_results = fread("./report/simulation_low_n.csv")
```

## Draw network plot

```{r message=FALSE, warning=FALSE}
library(dplyr)
network_research_id0 = simulation1_results %>%
  filter(network_type == 'small_world')

remove(simulation1_results)
```

```{r}
library(tidyr)
agent_info_id0 = network_research_id0 %>%
  filter(Step == 0) %>%
  select(AgentID, Agent_Type, Neighbors, Influencer, Neighbors_number)
```

```{r}
all_agents_data_id0 = network_research_id0 %>%
  filter(AgentID %in% 0:999) %>%
  select(AgentID, Step, Adopted) %>%
  arrange(Step) %>%
  pivot_wider(names_from = Step, values_from = Adopted, names_prefix = "Step") %>%
  left_join(agent_info_id0)
remove(agent_info_id0)
gc()
```

```{r}
library(jsonlite)
all_agents_data_id0$Neighbors = lapply(all_agents_data_id0$Neighbors, fromJSON)
```

```{r}
# library(igraph)
# create a list for edges
edges <- do.call(rbind, lapply(1:nrow(all_agents_data_id0), function(i) {
  agent_id <- all_agents_data_id0$AgentID[i]
  neighbors <- all_agents_data_id0$Neighbors[[i]]
  if(length(neighbors) > 0) {
    data.frame(from = agent_id, to = neighbors)
  } else {
    NULL
  }
}))

# remove the repeated edges
edges <- unique(edges)
gc()
```

```{r}
library(ggraph)
library(tidygraph)
library(igraph)

# create graph object
g <- graph_from_data_frame(edges, directed = FALSE)
# fix the position for each plot
layout <- layout_nicely(g)
# layout <- layout_on_grid(g)
# layout <- layout_randomly(g)

```

```{r fig.height=10, fig.width=10}
steps <- seq(0, 100, by = 10)

# write a loop to draw network plot
for (step in steps) {
  # transfer to tbl_graph object
  tg <- as_tbl_graph(g)
  
  # extract the StepN
  step_col <- paste0("Step", step)
  
  # node attribute settings
  tg <- tg %>%
    activate(nodes) %>%
    mutate(
      Influencer = all_agents_data_id0$Influencer[as.numeric(name) + 1],
      Agent_Type = all_agents_data_id0$Agent_Type[as.numeric(name) + 1],
      Adopted = all_agents_data_id0[[step_col]][as.numeric(name) + 1]
    )
  
  # draw network plot
  p <- ggraph(tg, layout = layout) +
    geom_edge_link(color = "grey") +
    geom_node_point(aes(size = as.factor(Influencer),
                        colour = as.factor(Adopted)),
                    show.legend = FALSE) +
    scale_size_manual(values = c('FALSE' = 6, 'TRUE' = 12)) +
    scale_color_manual(values = c('FALSE' = 'blue', 'TRUE' = 'red')) +
    theme_void() +
    ggtitle(paste("Step", step))
  
  # save the network plot
  ggsave(
    filename = paste0("./pic_network_graph/network_plot_step_", step, ".svg"),
    plot = p,
    width = 10,
    height = 10
  )
  gc()
}

gc()
```

```{r}

```
