---
title: "P Change Research"
author: "Zehao Qian"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Data Set: Simulation 1 and 6

-   N = 1000

-   p = 0.01, 0.02, 0.03

-   q = 0.3

-   Iteration = 25

```{r}
# --------------------------------------------------------
gc()
rm(list = ls())
graphics.off()
cat("\014")
# --------------------------------------------------------
folder_name <- "./pic_p_change_research"
if (dir.exists(folder_name)) {
  unlink(folder_name, recursive = TRUE)
}
dir.create(folder_name)
```

# Small World Network

```{r}
library(data.table)
simulation1_results = fread("./report/simulation1.csv")
```

```{r}
library(tidyr)
library(dplyr)

p.change.research = simulation1_results %>%
  filter(AgentID == 100, Step == 100)

data.p.change.long <- p.change.research %>%
  pivot_longer(cols = starts_with("Steps_to"), 
               names_to = "Step_Percent", 
               values_to = "Steps_Count") %>%
  mutate(p_number = case_when(
    p == 0.01 ~ "p = 0.01",
    p == 0.015 ~ "p = 0.015",
    p == 0.02 ~ "p = 0.02",
    p == 0.025 ~ "p = 0.025",
    p == 0.03 ~ "p = 0.03",
    TRUE ~ NA_character_  # other cases
  ))

```

```{r fig.height=6, fig.width=10}
library(ggplot2)

box = ggplot(data.p.change.long) +
  aes(x = p_number, y = Steps_Count) +
  geom_boxplot(color = 'black', fill = '#6888F5') +
  stat_summary(
    fun = median,
    geom = "text",
    aes(label = sprintf("%.1f", after_stat(y))),
    vjust = -0.5,
    color = "black",
    size = 3
  ) +
  scale_fill_gradient() +
  labs(
    x = "Different P Coefficient",
    y = "Steps Count",
    title = "Boxplot for Potential User Acceptance Ratio",
    subtitle = "When the acceptance probability of innovator changes (p)"
  ) +
  theme_light() +
  theme(
    plot.title = element_text(face = "bold", hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5)
  ) +
  facet_wrap(vars(Step_Percent)) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 80))

ggsave(
  "./pic_p_change_research/box_sm.svg",
  plot = box,
  device = "svg",
  height = 8,
  width = 12
)

ggsave(
  "./pic_p_change_research/box_sm.png",
  plot = box,
  device = "png",
  height = 8,
  width = 12
)

box
```

```{r fig.height=5, fig.width=9}

line.data = simulation1_results %>%
  filter(AgentID == 0)

# calculate the max, min and mean value of Adopted_Count for each step and p's combination
ribbon_data <- line.data %>%
  group_by(Step, p) %>%
  summarise(
    ymin = min(Adopted_Count),
    ymax = max(Adopted_Count),
    y_mean = mean(Adopted_Count)
  )

# create a combined-plot with both scatter and ribbon plot
combined_plot <- ggplot() +
  geom_ribbon(
    data = ribbon_data %>%
      filter(p %in% c(0.01, 0.02, 0.03)),
    aes(x = Step, ymin = ymin, ymax = ymax),
    alpha = 0.3,
    fill = "blue"
  ) +
  geom_line(
    data = ribbon_data %>% filter(p %in% c(0.01, 0.02, 0.03)),
    aes(x = Step, y = y_mean),
    color = "red",
    size = 1.5
  ) +
  geom_point(
    data = line.data %>% filter(p %in% c(0.01, 0.02, 0.03)),
    aes(x = Step, y = Adopted_Count),
    color = "purple",
    shape = "circle small",
    size = 0.8
  ) +
  scale_color_viridis_c() +
  labs(
    x = 'Steps Count',
    y = 'Adopted User Count',
    title = "Ribbon and Scatter Plot Comparison with Different P Coefficient",
    subtitle = "N=1000, iteration=25, Small World Network"
  ) +
  theme_light() +
  theme(
    plot.title = element_text(face = "bold", hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5)
  ) +
  facet_wrap(vars(p))

ggsave("./pic_p_change_research/combined_plot_sm.png",
       plot = combined_plot,
       device = "png",
       height = 6,
       width = 10)

ggsave("./pic_p_change_research/combined_plot_sm.svg",
       plot = combined_plot,
       device = "svg",
       height = 6,
       width = 10)

combined_plot
```

# Random Network

```{r}
# --------------------------------------------------------
gc()
rm(simulation1_results)
graphics.off()
cat("\014")

box1 = data.p.change.long

# --------------------------------------------------------
simulation7_results = fread("./report/simulation7.csv")
p.change.research = simulation7_results %>%
  filter(AgentID == 100, Step == 100)

data.p.change.long <- p.change.research %>%
  pivot_longer(cols = starts_with("Steps_to"), 
               names_to = "Step_Percent", 
               values_to = "Steps_Count") %>%
  mutate(p_number = case_when(
    p == 0.01 ~ "p = 0.01",
    p == 0.015 ~ "p = 0.015",
    p == 0.02 ~ "p = 0.02",
    p == 0.025 ~ "p = 0.025",
    p == 0.03 ~ "p = 0.03",
    TRUE ~ NA_character_  # other cases
  ))

```

```{r fig.height=6, fig.width=10}
library(ggplot2)

box = ggplot(data.p.change.long) +
  aes(x = p_number, y = Steps_Count) +
  geom_boxplot(color = 'black', fill = '#D77071') +
  stat_summary(
    fun = median,
    geom = "text",
    aes(label = sprintf("%.1f", after_stat(y))),
    vjust = -0.5,
    color = "black",
    size = 3
  ) +
  scale_fill_gradient() +
  labs(
    x = "Different P Coefficient",
    y = "Steps Count",
    title = "Boxplot for Potential User Acceptance Ratio",
    subtitle = "When the acceptance probability of innovator changes (p)"
  ) +
  theme_light() +
  theme(
    plot.title = element_text(face = "bold", hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5)
  ) +
  facet_wrap(vars(Step_Percent)) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 80))

ggsave(
  "./pic_p_change_research/box_random.svg",
  plot = box,
  device = "svg",
  height = 8,
  width = 12
)

ggsave(
  "./pic_p_change_research/box_random.png",
  plot = box,
  device = "png",
  height = 8,
  width = 12
)

box
```

```{r fig.height=5, fig.width=9}

line.data = simulation7_results %>%
  filter(AgentID == 0)

# calculate the max, min and mean value of Adopted_Count for each step and p's combination
ribbon_data <- line.data %>%
  group_by(Step, p) %>%
  summarise(
    ymin = min(Adopted_Count),
    ymax = max(Adopted_Count),
    y_mean = mean(Adopted_Count)
  )

# create a combined-plot with both scatter and ribbon plot
combined_plot <- ggplot() +
  geom_ribbon(
    data = ribbon_data %>%
      filter(p %in% c(0.01, 0.02, 0.03)),
    aes(x = Step, ymin = ymin, ymax = ymax),
    alpha = 0.3,
    fill = "blue"
  ) +
  geom_line(
    data = ribbon_data %>% filter(p %in% c(0.01, 0.02, 0.03)),
    aes(x = Step, y = y_mean),
    color = "red",
    size = 1.5
  ) +
  geom_point(
    data = line.data %>% filter(p %in% c(0.01, 0.02, 0.03)),
    aes(x = Step, y = Adopted_Count),
    color = "#903749",
    shape = "circle small",
    size = 0.8
  ) +
  scale_color_viridis_c() +
  labs(
    x = 'Steps Count',
    y = 'Adopted User Count',
    title = "Ribbon and Scatter Plot Comparison with Different P Coefficient",
    subtitle = "N=1000, iteration=25, Random Network"
  ) +
  theme_light() +
  theme(
    plot.title = element_text(face = "bold", hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5)
  ) +
  facet_wrap(vars(p))

ggsave("./pic_p_change_research/combined_plot_random.png",
       plot = combined_plot,
       device = "png",
       height = 6,
       width = 10)

ggsave("./pic_p_change_research/combined_plot_random.svg",
       plot = combined_plot,
       device = "svg",
       height = 6,
       width = 10)

combined_plot
```

```{r}
box7 = data.p.change.long
```

```{r}
box_full = rbind(box1, box7) %>%
  filter(Step_Percent == 'Steps_to_50_percent')
```

```{r fig.height=6, fig.width=10}
box_final = ggplot(box_full) +
  aes(x = p_number, y = Steps_Count, fill = network_type) +
  geom_boxplot(color = 'black') +
  # stat_summary(
  #   fun = median,
  #   geom = "text",
  #   aes(label = sprintf("%.1f", after_stat(y))),
  #   vjust = -0.5,
  #   color = "black",
  #   size = 3
  # ) +
  scale_fill_manual(values = c("small_world" = "#6888F5", "random" = "#D77071"),
                    name = "Network Type") +
  labs(
    x = "Different P Coefficient",
    y = "Steps Count",
    title = "Compare p in different networks",
    subtitle = "When 50% of the potential consumers accept"
  ) +
  theme_light() +
  theme(
    plot.title = element_text(face = "bold", hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5),
    legend.position = "bottom"
  ) +
  facet_wrap(vars(Step_Percent))


box_final

ggsave("./pic_p_change_research/box_final.png",
       plot = box_final,
       device = "png",
       height = 6,
       width = 10)

ggsave("./pic_p_change_research/box_final.svg",
       plot = box_final,
       device = "svg",
       height = 6,
       width = 10)
```

```{r}

```
