---
title: "Change of Innovator and Influencer Proportion"
author: "Zehao Qian"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# --------------------------------------------------------
gc()
rm(list = ls())
graphics.off()
cat("\014")
# --------------------------------------------------------
folder_name <- "./pic_prop_inno_inf_research"
if (dir.exists(folder_name)) {
  unlink(folder_name, recursive = TRUE)
}
dir.create(folder_name)
```

# Small World Network

Data Set: Simulation 6

-   N = 1000

-   p = 0.01

-   q = 0.3

-   Iteration = 25

-   Innovator Prop = 0.1, 0.2, 0.3, 0.4, 0.5

-   Influencer Prop = 0.01

-   Influential Innovator Prop = [0, 0.003, 0.005, 0.007, 0.01]

```{r}
library(data.table)
simulation6_results = fread("./report/simulation6.csv")
```

```{r}
library(tidyr)
library(dplyr)
library(ggplot2)

data.research = simulation6_results %>%
  filter(AgentID == 0, Step == 100)
```

```{r}
library(jsonlite)
data.research$agent_proportion_list = lapply(
  data.research$agent_proportion, 
  fromJSON)
```

```{r}
data.research$prop_inf = sapply(data.research$agent_proportion_list,
                                function(x) x[1]+x[2])
data.research$prop_inno = sapply(data.research$agent_proportion_list, 
                                function(x) x[1]+x[3])
```

```{r}
data.research.heat = data.research %>%
  select(
    p,
    q,
    Steps_to_25_percent,
    Steps_to_50_percent,
    Steps_to_75_percent,
    prop_inf,
    prop_inno
  )
```

```{r}
data.research.heat.result <- data.research.heat %>%
  group_by(prop_inno, prop_inf) %>%
  summarise(
    avg_steps_25 = mean(Steps_to_25_percent),
    avg_steps_50 = mean(Steps_to_50_percent),
    avg_steps_75 = mean(Steps_to_75_percent)
  ) %>%
  ungroup()
```

```{r fig.height=5, fig.width=5}
step_to_25 = ggplot(data.research.heat.result) +
  aes(x = prop_inno, y = prop_inf, fill = avg_steps_25) +
  geom_tile() +
  geom_text(aes(label = round(avg_steps_25, 1)), color = "white", size = 3) +
  scale_fill_viridis_c(option = "viridis", direction = 1) +
  theme_light() +
  labs(
    x = "Change the Proportion of Innovators",
    y = "Change the Proportion of Influencers",
    title = "Heatmap for Proportion Research",
    subtitle = "p = 0.01, q = 0.3",
    fill = "Average Steps to \n 25 percentage"
  ) +
  theme(
    plot.title = element_text(face = "bold", hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5)
  ) +
  guides(fill = "none", colour = "none")

ggsave("./pic_prop_inno_inf_research/step_to_25_sm.png",
       plot = step_to_25,
       device = "png",
       height = 5,
       width = 5)

step_to_25
```

```{r fig.height=5, fig.width=5}
step_to_50 = ggplot(data.research.heat.result) +
  aes(x = prop_inno, y = prop_inf, fill = avg_steps_50) +
  geom_tile() +
  geom_text(aes(label = round(avg_steps_50, 1)), color = "white", size = 3) +
  scale_fill_viridis_c(option = "viridis", direction = 1) +
  theme_light() +
  labs(
    x = "Change the Proportion of Innovators",
    y = "Change the Proportion of Influencers",
    title = "Heatmap for Proportion Research",
    subtitle = "p = 0.01, q = 0.3",
    fill = "Average Steps to \n 50 percentage"
  ) +
  theme(
    plot.title = element_text(face = "bold", hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5)
  ) +
  guides(fill = "none", colour = "none")

ggsave("./pic_prop_inno_inf_research/step_to_50_sm.png",
       plot = step_to_50,
       device = "png",
       height = 5,
       width = 5)

step_to_50
```

```{r fig.height=5, fig.width=5}
step_to_75 = ggplot(data.research.heat.result) +
  aes(x = prop_inno, y = prop_inf, fill = avg_steps_75) +
  geom_tile() +
  geom_text(aes(label = round(avg_steps_75, 1)), color = "white", size = 3) +
  scale_fill_viridis_c(option = "viridis", direction = 1) +
  theme_light() +
  labs(
    x = "Change the Proportion of Innovators",
    y = "Change the Proportion of Influencers",
    title = "Heatmap for Proportion Research",
    subtitle = "p = 0.01, q = 0.3",
    fill = "Average Steps to \n 75 percentage"
  ) +
  theme(
    plot.title = element_text(face = "bold", hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5)
  ) +
  guides(fill = "none", colour = "none")

ggsave("./pic_prop_inno_inf_research/step_to_75_sm.png",
       plot = step_to_75,
       device = "png",
       height = 5,
       width = 5)

step_to_75
```

# Random Network

```{r}
# --------------------------------------------------------
gc()
rm(list = ls())
graphics.off()
cat("\014")
# --------------------------------------------------------
simulation12_results = fread("./report/simulation12.csv")
data.research = simulation12_results %>%
  filter(AgentID == 0, Step == 100)

data.research$agent_proportion_list = lapply(
  data.research$agent_proportion, 
  fromJSON)

data.research$prop_inf = sapply(data.research$agent_proportion_list,
                                function(x) x[1]+x[2])
data.research$prop_inno = sapply(data.research$agent_proportion_list, 
                                function(x) x[1]+x[3])

data.research.heat = data.research %>%
  select(
    p,
    q,
    Steps_to_25_percent,
    Steps_to_50_percent,
    Steps_to_75_percent,
    prop_inf,
    prop_inno
  )

data.research.heat.result <- data.research.heat %>%
  group_by(prop_inno, prop_inf) %>%
  summarise(
    avg_steps_25 = mean(Steps_to_25_percent),
    avg_steps_50 = mean(Steps_to_50_percent),
    avg_steps_75 = mean(Steps_to_75_percent)
  ) %>%
  ungroup()
```

```{r fig.height=5, fig.width=5}
step_to_25 = ggplot(data.research.heat.result) +
  aes(x = prop_inno, y = prop_inf, fill = avg_steps_25) +
  geom_tile() +
  geom_text(aes(label = round(avg_steps_25, 1)), color = "white", size = 3) +
  scale_fill_viridis_c(option = "magma", direction = 1) +
  theme_light() +
  labs(
    x = "Change the Proportion of Innovators",
    y = "Change the Proportion of Influencers",
    title = "Heatmap for Proportion Research",
    subtitle = "p = 0.01, q = 0.3",
    fill = "Average Steps to \n 25 percentage"
  ) +
  theme(
    plot.title = element_text(face = "bold", hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5)
  ) +
  guides(fill = "none", colour = "none")

ggsave("./pic_prop_inno_inf_research/step_to_25_random.png",
       plot = step_to_25,
       device = "png",
       height = 5,
       width = 5)

step_to_25
```

```{r fig.height=5, fig.width=5}
step_to_50 = ggplot(data.research.heat.result) +
  aes(x = prop_inno, y = prop_inf, fill = avg_steps_50) +
  geom_tile() +
  geom_text(aes(label = round(avg_steps_50, 1)), color = "white", size = 3) +
  scale_fill_viridis_c(option = "magma", direction = 1) +
  theme_light() +
  labs(
    x = "Change the Proportion of Innovators",
    y = "Change the Proportion of Influencers",
    title = "Heatmap for Proportion Research",
    subtitle = "p = 0.01, q = 0.3",
    fill = "Average Steps to \n 50 percentage"
  ) +
  theme(
    plot.title = element_text(face = "bold", hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5)
  ) +
  guides(fill = "none", colour = "none")

ggsave("./pic_prop_inno_inf_research/step_to_50_random.png",
       plot = step_to_50,
       device = "png",
       height = 5,
       width = 5)

step_to_50
```

```{r fig.height=5, fig.width=5}
step_to_75 = ggplot(data.research.heat.result) +
  aes(x = prop_inno, y = prop_inf, fill = avg_steps_75) +
  geom_tile() +
  geom_text(aes(label = round(avg_steps_75, 1)), color = "white", size = 3) +
  scale_fill_viridis_c(option = "magma", direction = 1) +
  theme_light() +
  labs(
    x = "Change the Proportion of Innovators",
    y = "Change the Proportion of Influencers",
    title = "Heatmap for Proportion Research",
    subtitle = "p = 0.01, q = 0.3",
    fill = "Average Steps to \n 75 percentage"
  ) +
  theme(
    plot.title = element_text(face = "bold", hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5)
  ) +
  guides(fill = "none", colour = "none")

ggsave("./pic_prop_inno_inf_research/step_to_75_random.png",
       plot = step_to_75,
       device = "png",
       height = 5,
       width = 5)

step_to_75
```

```{r}

```
