---
title: "Model 5 Result Plot Analysis"
author: "Zehao Qian"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Visualization for Model version 5 (Boxplot)

Box Plot Analysis with 'Esquisse' Package

## Environment Setup

```{r}
# --------------------------------------------------------
# clear the environment var area
rm(list = ls())
# clear all plots
graphics.off()
# clear the console area
cat("\014")
# --------------------------------------------------------
# name of pic output folder
folder_name <- "./pic"

# check if the folder already exists
if (dir.exists(folder_name)) {
  unlink(folder_name, recursive = TRUE)
}

# create a new folder
dir.create(folder_name)
```

## Read data with 'Fread' function

```{r message=FALSE, warning=FALSE}
library(data.table)
model5.results = fread("./model5results.csv")
```

## Filter data only when p=0.01, 0.02, 0,03

```{r message=FALSE, warning=FALSE}
library(dplyr)
p.change.research = model5.results %>% filter(AgentID == 100, Step == 100)
# p.change.research
```

## Change the data to long format

```{r}
library(tidyr)
p.change.research.long <- p.change.research %>%
  pivot_longer(cols = starts_with("Steps_to"), 
               names_to = "Step_Percent", 
               values_to = "Steps_Count")
p.change.research.long
```

## Draw Box Plot

### Generate Box plot with "esquisse"

```{r}
# library(plotly)
# library(esquisse)
# esquisser()
```

```{r fig.height=9, fig.width=16}
library(ggplot2)
box = ggplot(p.change.research.long) +
  aes(x = Step_Percent, y = Steps_Count, fill = p) +
  geom_boxplot() +
  scale_fill_gradient() +
  labs(
    x = "Proportion Reach",
    y = "Steps Count",
    title = "Boxplot for Potential User Acceptance Ratio",
    subtitle = "When the acceptance probability of innovator changes (p)"
  ) +
  theme_light() +
  theme(
    plot.title = element_text(face = "bold", hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5)
  ) +
  facet_wrap(vars(p))

# Show the plot
box
```

### Save the Box Plot

```{r}
library(svglite)
ggsave("./pic/boxplot_p_change.png", plot = box, device = "png", height = 9, width = 16)
```

# Visualization for Model version 5 (Line chart)

```{r}
# same p, q, RunID, different
line.data = model5.results %>%
  filter(AgentID == 0)
```

```{r fig.height=6, fig.width=10}
line = ggplot(line.data) +
  aes(
    x = Step,
    y = Adopted_Count,
    colour = iteration,
    group = iteration
  ) +
  geom_line(linewidth = 0.6) +
  scale_color_viridis_c(option = "magma", direction = 1) +
  labs(
    x = 'Steps Count',
    y = 'Adopted User Count',
    title = "Line Chart Comparison with Different P Value", subtitle = "N=1000, iteration=25") +
  theme_light() +
  theme(
    plot.title = element_text(face = "bold", hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5)
  ) +
  facet_wrap(vars(p))

# Show the plot
line
```

```{r}
ggsave("./pic/linechart_p_change.png", plot = line, device = "png", height = 6, width = 10)
```

```{r}
agent_inno.line.data= model5.results %>%
  filter(iteration == 0) %>%
  select(p, Step, Innovator_Count, Imitator_Count, Adopted_Count)
```

```{r}
agent_inf.line.data= model5.results %>%
  filter(iteration == 0) %>%
  select(p, Step, Influencer_Count, Non_Influencer_Count, Adopted_Count)
```

```{r}
agent_inno.line.data.long = agent_inno.line.data %>%
  pivot_longer(cols = c(Innovator_Count, Imitator_Count,  Adopted_Count), 
               names_to = "Type",
               values_to = "Count")
```

```{r}
agent_inf.line.data.long = agent_inf.line.data %>%
  pivot_longer(cols = c(Influencer_Count, Non_Influencer_Count,  Adopted_Count), 
               names_to = "Type",
               values_to = "Count")
```

```{r fig.height=6, fig.width=10}
p.line.inno = ggplot(agent_inno.line.data.long) +
  aes(x = Step, y = Count, colour = Type) +
  geom_line(linewidth = 0.8) +
  scale_color_viridis_d(option = "plasma", direction = 1) +
  labs(
    x = "Steps Count",
    y = "Adopted User Count",
    title = "Innovator and Imitator Statistics",
    subtitle = "Iteration = 0",
    color = "Innovator or Imitator"
  ) +
  theme_light() +
  theme(
    plot.title = element_text(face = "bold", hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5)
  ) +
  facet_wrap(vars(p))

p.line.inno
```

```{r}
ggsave("./pic/linechart_inno.png",
       plot = p.line.inno,
       device = "png",
       height = 6,
       width = 10)
```

```{r fig.height=6, fig.width=10}
p.line.inf = ggplot(agent_inf.line.data.long) +
  aes(x = Step, y = Count, colour = Type) +
  geom_line(linewidth = 0.8) +
  scale_color_viridis_d(option = "plasma", direction = 1) +
  labs(
    x = "Steps Count",
    y = "Adopted User Count",
    title = "Influencers' Statistics",
    subtitle = "Iteration = 0",
    color = "Influencer or not"
  ) +
  theme_light() +
  theme(
    plot.title = element_text(face = "bold", hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5)
  ) +
  facet_wrap(vars(p))

p.line.inf
```

```{r}
ggsave("./pic/linechart_inf.png",
       plot = p.line.inf,
       device = "png",
       height = 6,
       width = 10)
```

```{r}

```
