---
title: "Network Visualization"
author: "Zehao Qian"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Network Visualization for Model 5 Result

## Draw network plot

```{r}
network.research.0 = model5.results %>%
  filter(RunId == 0)
```

```{r}
data_long <- tibble(
  step = paste0("step", 0:100),
  value = NA
)

data_wide <- data_long %>%
  pivot_wider(names_from = step, values_from = value)
```

```{r}
agent.0 = network.research %>%
  filter(AgentID == 0) %>%
  select(Adopted)
```

```{r}
agent.1 = network.research %>%
  filter(AgentID == 1)
```

```{r}
network.0 = network.research %>%
  filter(Step == 50)
```

```{r}
library(jsonlite)
network.0$Neighbors.new = lapply(network.0$Neighbors, fromJSON)
```

```{r}
# library(igraph)
# create a list for edges
edges <- do.call(rbind, lapply(1:nrow(network.0), function(i) {
  agent_id <- network.0$AgentID[i]
  neighbors <- network.0$Neighbors.new[[i]]
  if(length(neighbors) > 0) {
    data.frame(from = agent_id, to = neighbors)
  } else {
    NULL
  }
}))

# remove the repeated edges
edges <- unique(edges)
```

```{r}
library(ggraph)
library(tidygraph)
library(igraph)

# create graph object
g <- graph_from_data_frame(edges, directed = FALSE)

# transfer to tbl_graph object
tg <- as_tbl_graph(g)

# add Influencer attribute to node
# tg <- tg %>%
#   activate(nodes) %>%
#   mutate(Influencer = network.0$Influencer[as.numeric(name) + 1])


tg <- tg %>%
  activate(nodes) %>%
  mutate(Influencer = network.0$Influencer[as.numeric(name) + 1],
         Agent_Type = network.0$Agent_Type[as.numeric(name) + 1],
         Adopted = network.0$Adopted[as.numeric(name) + 1])
```

```{r fig.height=10, fig.width=10}

layout <- layout_with_fr(g)
```

```{r fig.height=10, fig.width=10}
ggraph(tg, layout = layout) + 
  geom_edge_link(color = "grey") + 
  geom_node_point(aes(size = as.factor(Influencer), colour = as.factor(Adopted)), show.legend = FALSE) + 
  # geom_node_text(aes(label = name), repel = TRUE) + 
  scale_size_manual(values = c('FALSE' = 3, 'TRUE' = 6)) + 
  scale_color_manual(values = c('FALSE' = 'blue', 'TRUE'='red'))
  theme_void()
```

```{r}
gc()
```
