---
title: "Visual4Model5"
author: "Zehao Qian"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Visualization for ABM Model version 5

Box Plot Analysis with 'Esquisse' Package

## Environment Setup

```{r}
# --------------------------------------------------------
# clear the environment var area
rm(list = ls())
# clear all plots
graphics.off()
# clear the console area
cat("\014")
# --------------------------------------------------------
# name of pic output folder
folder_name <- "./pic"

# check if the folder already exists
if (dir.exists(folder_name)) {
  unlink(folder_name, recursive = TRUE)
}

# create a new folder
dir.create(folder_name)
```

## Read data with 'Fread' function

```{r message=FALSE, warning=FALSE}
library(data.table)
model5.results = fread("./model5results.csv")
```

## Filter data only when p=0.01, 0.02, 0,03

```{r message=FALSE, warning=FALSE}
library(dplyr)
p.change.research = model5.results %>% filter(AgentID == 100, Step == 100)
# p.change.research
```

## Change the data to long format

```{r}
library(tidyr)
p.change.research.long <- p.change.research %>%
  pivot_longer(cols = starts_with("Steps_to"), 
               names_to = "Step_Percent", 
               values_to = "Steps_Count")
p.change.research.long
```

## Draw Box Plot

### Generate Box plot with "esquisse"

```{r}
# library(plotly)
# library(esquisse)
# esquisser()
```

```{r fig.height=9, fig.width=16}
library(ggplot2)
box = ggplot(p.change.research.long) +
  aes(x = Step_Percent, y = Steps_Count, fill = p) +
  geom_boxplot() +
  scale_fill_gradient() +
  labs(
    x = "Proportion Reach",
    y = "Steps Count",
    title = "Boxplot for Potential User Acceptance Ratio",
    subtitle = "When the acceptance probability of innovator changes (p)"
  ) +
  theme_light() +
  theme(
    plot.title = element_text(face = "bold", hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5)
  ) +
  facet_wrap(vars(p))

# Show the plot
box
```

### Save the Box Plot

```{r}
library(svglite)
ggsave("./pic/boxplot_p_change.svg", plot = box, device = "svg", height = 9, width = 16)
```

## Draw network plot

```{r}
network.research.0 = model5.results %>%
  filter(RunId == 0)
```

```{r}
data_long <- tibble(
  step = paste0("step", 0:100),
  value = NA
)

data_wide <- data_long %>%
  pivot_wider(names_from = step, values_from = value)
```

```{r}
agent.0 = network.research %>%
  filter(AgentID == 0) %>%
  select(Adopted)
```

```{r}
agent.1 = network.research %>%
  filter(AgentID == 1)
```

```{r}
network.0 = network.research %>%
  filter(Step == 50)
```

```{r}
library(jsonlite)
network.0$Neighbors.new = lapply(network.0$Neighbors, fromJSON)
```

```{r}
# library(igraph)
# create a list for edges
edges <- do.call(rbind, lapply(1:nrow(network.0), function(i) {
  agent_id <- network.0$AgentID[i]
  neighbors <- network.0$Neighbors.new[[i]]
  if(length(neighbors) > 0) {
    data.frame(from = agent_id, to = neighbors)
  } else {
    NULL
  }
}))

# remove the repeated edges
edges <- unique(edges)
```

```{r}
library(ggraph)
library(tidygraph)
library(igraph)

# create graph object
g <- graph_from_data_frame(edges, directed = FALSE)

# transfer to tbl_graph object
tg <- as_tbl_graph(g)

# add Influencer attribute to node
# tg <- tg %>%
#   activate(nodes) %>%
#   mutate(Influencer = network.0$Influencer[as.numeric(name) + 1])


tg <- tg %>%
  activate(nodes) %>%
  mutate(Influencer = network.0$Influencer[as.numeric(name) + 1],
         Agent_Type = network.0$Agent_Type[as.numeric(name) + 1],
         Adopted = network.0$Adopted[as.numeric(name) + 1])
```

```{r fig.height=10, fig.width=10}

layout <- layout_with_fr(g)
```

```{r fig.height=10, fig.width=10}
ggraph(tg, layout = layout) + 
  geom_edge_link(color = "grey") + 
  geom_node_point(aes(size = as.factor(Influencer), colour = as.factor(Adopted)), show.legend = FALSE) + 
  # geom_node_text(aes(label = name), repel = TRUE) + 
  scale_size_manual(values = c('FALSE' = 3, 'TRUE' = 6)) + 
  scale_color_manual(values = c('FALSE' = 'blue', 'TRUE'='red'))
  theme_void()
```

```{r}
gc()
```
